inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
